export const fieldLabels = {
  name: "Name",
  legalName: "Legal Name",
  acronym: "Acronym",
  recognitionNumber: "Recognition Number",
  email: "Email",
  website: "Website",
  listOfStandardFeesUrl: "List of Standard Fees URL",
  hasCompanyNumber: "Does the organisation have a Company Number?",
  companyNumber: "Company Number",
  hasCharityNumber: "Does the organisation have a Charity Number?",
  charityNumber: "Charity Number",
  isOtherUkLegalEntity: "Is the organisation an other UK legal entity type?",
  otherLegalEntityType: "Other Legal Entity Type",
  isRegisteredInOtherCountry:
    "Is the organisation registered in another country?",
  otherCountryOfRegistration: "Other Country of Registration",
  otherCountryIdentifier: "Other Country Identifier",
  isIndividualOrPartnership:
    "Is the organisation an Individual or Partnership?",
  ofqualRecognisedOnDate: "Recognised On",
  ofqualSurrenderedDate: "Surrendered On",
  ofqualWithdrawnOnDate: "Withdrawn On",
  cceaRecognisedOnDate: "CCEA Recognised On",
  cceaSurrenderedDate: "CCEA Surrendered On",
  cceaWithdrawnOnDate: "CCEA Withdrawn On",
  line1: "Line 1",
  line2: "Line 2",
  line3: "Line 3",
  line4: "Line 4",
  postCode: "Post Code",
  country: "Country",
  phoneNumber: "Phone Number",
};
