import { OrganisationChange } from "./OrganisationChange";

export type Organisation = {
  id: string;
  accreditation: boolean;
  acronym: string;
  createdByUpn: string;
  createdByDisplayName: string;
  modifiedByUpn: string;
  modifiedByDisplayName: string;
  assignedToUpn: string;
  assignedToDisplayName: string;
  email: string;
  legalName: string;
  listOfStandardFeesUrl: string;
  itemId: number;
  name: string;
  recognitionNumber: string;
  website: string;
  updateStatus?: number;
  hasCompanyNumber: boolean;
  companyNumber: string;
  hasCharityNumber: boolean;
  charityNumber?: string;
  isOtherUkLegalEntity: boolean;
  otherLegalEntityType?: number;
  isRegisteredInOtherCountry: boolean;
  otherCountryOfRegistration?: string;
  otherCountryIdentifier?: string;
  isIndividualOrPartnership: boolean;
  line1: string;
  line2: string;
  line3: string;
  line4: string;
  postCode: string;
  country: string;
  phoneNumber: string;
  ofqualRecognisedOnDate?: Date;
  cceaRecognisedOnDate?: Date;
  ofqualSurrenderedDate?: Date;
  cceaSurrenderedDate?: Date;
  ofqualWithdrawnOnDate?: Date;
  cceaWithdrawnOnDate?: Date;
  organisationChanges: OrganisationChange[];
  createdDate: Date;
  modifiedDate: Date;
};
