import { MODULE_NAME } from "../moduleName";

export const CLEAR_ERROR_ORGANISATION_LIST = `${MODULE_NAME}/CLEAR_ERROR_ORGANISATION_LIST`;
export const LOADED_ORGANISATION_LIST = `${MODULE_NAME}/LOADED_ORGANISATION_LIST`;
export const LOADING_ORGANISATION_LIST = `${MODULE_NAME}/LOADING_ORGANISATION_LIST`;
export const LOADING_ORGANISATION_LIST_ERROR = `${MODULE_NAME}/LOADING_ORGANISATION_LIST_ERROR`;

export const CLEAR_ERROR_ORGANISATION = `${MODULE_NAME}/CLEAR_ERROR_ORGANISATION`;
export const LOADED_ORGANISATION = `${MODULE_NAME}/LOADED_ORGANISATION`;
export const LOADING_ORGANISATION = `${MODULE_NAME}/LOADING_ORGANISATION`;
export const LOADING_ORGANISATION_ERROR = `${MODULE_NAME}/LOADING_ORGANISATION_ERROR`;

export const EDIT_ORGANISATION = `${MODULE_NAME}/EDIT_ORGANISATION`;
export const EDIT_ORGANISATION_SUCCESS = `${MODULE_NAME}/EDIT_ORGANISATION_SUCCESS`;
export const EDIT_ORGANISATION_ERROR = `${MODULE_NAME}/EDIT_ORGANISATION_ERROR`;

export const LOADING_ACTIVITIES = `${MODULE_NAME}/LOADING_ACTIVITIES`;
export const LOADED_ACTIVITIES = `${MODULE_NAME}/LOADED_ACTIVITIES`;

export const APPROVING_CHANGE = `${MODULE_NAME}/APPROVING_CHANGE`;
export const APPROVED_CHANGE = `${MODULE_NAME}/APPROVED_CHANGE`;
